### ISSUE TITLE
Instructions manquantes dans le README pour exécuter votre projet

### ISSUE THREAD

**Issue by tbezierslafosse** [Meliothep/RogueTD#1]
Bonjour,
Joli jeu, ça marche bien c'est cool.
Vous pouvez ajouter ça à votre README pour lancer le jeu en ligne de commande.
`mvn clean package exec:java '-Dexec.mainClass="game.RogueTD"'`
Sinon on est forcé de passer par un IDE et c'est pas pratique :)

**Comment by Meliothep** [comment]
Merci, quand j'aurai une première version "complète" (avec au moins les menus finis, un second type de tour et SI POSSIBLE un début d'arbre d'amélioration) j'essaierai de publier un artéfact exécutable.
